name: flutter_installer_cli
description: Installation toolkit for Java, Android, and Flutter SDK on Windows, Linux, and MacOS PCs.
version: 0.4.1
authors: Abiyyu Daffa Alam <daffaalam@gmail.com>
repository: https://github.com/daffaalam/flutter_installer_cli
issue_tracker: https://github.com/daffaalam/flutter_installer_cli/issues
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  dio: ^3.0.10
  process_run: ^0.10.12+3
  archive: ^2.0.13
  sentry: ^3.0.1
  xml: ^4.4.1
